[package]
name = "interledger-packet"
version = "0.2.1"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger packet serialization/deserialization"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/emschwartz/interledger-rs"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.12"
chrono = "0.4.6"
hex = "0.3.2"
quick-error = "1.2.2"

[dev-dependencies]
criterion = "0.2.10"
lazy_static = "1.3.0"

[[bench]]
name = "packets"
harness = false
