[package]
name = "ilp"
version = "0.3.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"

[dependencies]
byteorder = "1.0.0"
chrono = "0.4.4"
futures = "0.1.23"
hex = "0.3.2"
lazy_static = "1.0.1"
num-bigint = "0.2.0"
quick-error = "1.2.0"
tokio = "0.1.8"
tokio-tungstenite = "0.6.0"
tokio-tcp = "0.1.1"
tungstenite = "0.6.0"
url = "1.7.1"