[package]
name = "interledger"
version = "0.2.1"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"

# Optional feature to log connection statistics using a CSV file
[features]
metrics_csv = ["csv"]

[dependencies]
base64 = "0.10.0"
byteorder = "1.2.7"
bytes = "0.4.11"
chrono = "0.4.6"
clap = "2.32.0"
csv = { version = "1.0.2", optional = true }
env_logger = "0.6.0"
failure = "0.1.3"
failure_derive = "0.1.3"
futures = "0.1.25"
hex = "0.3.2"
hyper = "0.12.17"
lazy_static = "1.2.0"
log = "0.4.6"
num-bigint = "0.2.1"
num-traits = "0.2.6"
parking_lot = "0.7.0"
quick-error = "1.2.2"
reqwest = "0.9.5"
rand = "0.6.1"
ring = "0.13.5"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
stream-cancel = "0.4.4"
tokio = "0.1.13"
tokio-io = "0.1.10"
tokio-tungstenite = "0.6.0"
tokio-tcp = "0.1.2"
tungstenite = "0.6.1"
url = "1.7.2"

[badges]
circle-ci = { repository = "emschwartz/interledger-rs" }
codecov = { repository = "emschwartz/interledger-rs" }
