[package]
name = "interledger-util"
version = "0.1.0"
authors = ["Taiga Nakayama <dora@dora-gt.jp>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.1.25"
bytes = "0.4.12"
hyper = "0.12.25"
