[package]
name = "interledger-store-redis"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Data store for Interledger.js using Redis"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "interledger_store_redis"
path = "src/lib.rs"

[dependencies]
bytes = "0.4.11"
clap = "2.32.0"
futures = "0.1.25"
hashbrown = "0.1.8"
interledger-btp = { path = "../interledger-btp" }
interledger-http = { path = "../interledger-http" }
interledger-ildcp = { path = "../interledger-ildcp" }
interledger-router = { path = "../interledger-router" }
interledger-service = { path = "../interledger-service" }
interledger-service-util = { path = "../interledger-service-util" }
log = "0.4.6"
parking_lot = "0.7.1"
redis = "0.10.0"
url = "1.7.2"
tokio-executor = "0.1.6"
tokio-timer = "0.2.10"