version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt-preview
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Build
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: project-cache
          paths:
            - "./target"