version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
        environment:
          CARGO_HOME: /home/circleci/.cargo
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-1-{{ checksum "Cargo.toml" }}-{{ .Branch }}
            - cargo-cache-1-{{ checksum "Cargo.toml" }}
            - cargo-cache-1-
      - run:
          name: Install Cargo Extensions
          command: |
            cargo install --quiet cargo-audit || true # cargo-kcov
            rustup component add rustfmt clippy || true
      - run:
          name: Install Redis
          # Install from stretch-backports to get the latest version
          # The normal repository has version 3.2, which doesn't support redis modules
          command: |
            echo "deb http://deb.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get -t stretch-backports install redis-server
            redis-server --version
      - run:
          name: Build
          command: cargo build --all-features --all-targets
      - run:
          name: Test
          command: cargo test --all --all-features
          environment:
            RUST_BACKTRACE: "1"
      - run:
          name: Check Style
          command: |
            cargo fmt --all -- --check
            cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: Audit Dependencies
          command: cargo audit
      # - run:
      #     name: Install kcov
      #     command: >-
      #       kcov --version ||
      #       (sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
      #       && cargo kcov --print-install-kcov-sh | sh)
      # - run:
      #     name: Generate Coverage Report
      #     # Enable sudo to avoid the error: "Can't set personality: Operation not permitted"
      #     # See discussion in https://github.com/travis-ci/travis-ci/issues/9061
      #     sudo: required
      #     command:
      #       cargo kcov --all --verbose
      #       # -- --verify
      #       # --exclude-region="kcov-ignore-start:kcov-ignore-end"
      #       # --exclude-pattern="$CARGO_HOME,**/tests/**"
      #       # --exclude-line="^(\)*\}*,*)$"
      #     environment:
      #       # Configure the redis tests to use a unix socket instead of TCP
      #       REDISRS_SERVER_TYPE: unix
      # - run:
      #     name: Upload Code Coverage
      #     command: "bash <(curl -s https://codecov.io/bash)"
      - save_cache:
          key: cargo-cache-1-{{ checksum "Cargo.toml" }}-{{ .Branch }}
          paths:
            - /home/circleci/.cargo
