version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
        environment:
          CARGO_HOME: /home/circleci/.cargo
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-v4-{{ checksum "Cargo.toml" }}-{{ .Branch }}
            - project-v4-{{ checksum "Cargo.toml" }}
            - project-v4-
      - run:
          name: Install Cargo Extensions
          command: cargo install --quiet cargo-kcov cargo-audit || true
      - run:
          name: Install rustfmt
          command: rustup component add rustfmt || true
      - run:
          name: Install kcov
          command: >-
            sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
            && cargo kcov --print-install-kcov-sh | sh
      - run:
          name: Install Redis
          # Install from stretch-backports to get the latest version
          # The normal repository has version 3.2, which doesn't support redis modules
          command: >-
            echo "deb http://deb.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list
            && sudo apt-get update
            && sudo apt-get -t stretch-backports install redis-server
            && redis-server --version
      - run:
          name: Build + Test
          command: cargo test --all --all-features
          environment:
            # Configure the redis tests to use a unix socket instead of TCP
            REDISRS_SERVER_TYPE: unix
      - run:
          name: Check Formatting
          command: cargo fmt --all -- --check
      - run:
          name: Audit Dependencies
          command: cargo audit
      - run:
          name: Generate Coverage Report
          command:
            cargo kcov --all --verbose
            # -- --verify
            # --exclude-region="kcov-ignore-start:kcov-ignore-end"
            # --exclude-pattern="$CARGO_HOME,**/tests/**"
            # --exclude-line="^(\)*\}*,*)$"
          environment:
            # Configure the redis tests to use a unix socket instead of TCP
            REDISRS_SERVER_TYPE: unix
      - run:
          name: Upload Code Coverage
          command: "bash <(curl -s https://codecov.io/bash)"
      - save_cache:
          key: project-v4-{{ checksum "Cargo.toml" }}-{{ .Branch }}
          paths:
            - ./target
            - /home/circleci/.cargo
