[package]
name = "interledger-btp"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Bilateral Transfer Protocol (BTP) client and server services for Interledger.rs"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "0.4.11"
byteorder = "1.3.1"
chrono = "0.4.6"
futures = "0.1.25"
hashbrown = "0.1.8"
interledger-packet = { path = "../interledger-packet" }
interledger-service = { path = "../interledger-service" }
log = "0.4.6"
num-bigint = "0.2.2"
parking_lot = "0.7.1"
quick-error = "1.2.2"
rand = "0.6.5"
stream-cancel = "0.4.4"
tokio-executor = "0.1.6"
tokio-io = "0.1.12"
tokio-tcp = "0.1.3"
tokio-tungstenite = "0.6.0"
tungstenite = "0.6.1"
url = "1.7.2"

[dev-dependencies]
hex = "0.3.2"
lazy_static = "1.2.0"