[package]
name = "interledger-ccp"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Implementation of the Interledger Dynamic Configuration Protocol (ILDCP)"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/emschwartz/interledger-rs"

[dependencies]
bytes = "0.4.12"
byteorder = "1.3.1"
futures = "0.1.25"
hex = "0.3.2"
interledger-ildcp = { path = "../interledger-ildcp", version = "0.2.1" }
interledger-packet = { path = "../interledger-packet", version = "0.2.1" }
interledger-service = { path = "../interledger-service", version = "0.2.1" }
lazy_static = "1.3.0"
log = "0.4.6"
parking_lot = "0.7.1"
ring = "0.14.6"
tokio-executor = "0.1.7"
tokio-timer = "0.2.10"
