[package]
name = "interledger-stream"
version = "0.2.1"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Client and server implementations of the STREAM transport protocol"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/emschwartz/interledger-rs"

# Optional feature to log connection statistics using a CSV file
[features]
metrics_csv = ["csv"]

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
byteorder = "1.3.1"
chrono = "0.4.6"
csv = { version = "1.0.5", optional = true }
failure = "0.1.5"
futures = "0.1.25"
hashbrown = "0.1.8"
hex = "0.3.2"
interledger-ildcp = { path = "../interledger-ildcp", version = "0.2.1" }
interledger-packet = { path = "../interledger-packet", version = "0.2.1" }
interledger-service = { path = "../interledger-service", version = "0.2.1" }
log = "0.4.6"
parking_lot = "0.7.1"
ring = "0.14.6"

[dev-dependencies]
env_logger = "0.6.1"
interledger-router = { path = "../interledger-router", version = "0.2.1" }
lazy_static = "1.3.0"
regex = "1.1.6"
tokio = "0.1.16"
