[package]
name = "interledger-spsp"
version = "0.2.1"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Client and server implementations of the Simple Payment Setup Protocol (SPSP)"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/interledger-rs/interledger-rs"

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
failure = "0.1.5"
futures = "0.1.25"
hyper = "0.12.25"
interledger-ildcp = { path = "../interledger-ildcp", version = "0.2.1" }
interledger-packet = { path = "../interledger-packet", version = "0.2.1", features = ["serde"] }
interledger-service = { path = "../interledger-service", version = "0.2.1" }
interledger-stream = { path = "../interledger-stream", version = "0.2.1" }
log = "0.4.6"
reqwest = "0.9.11"
serde = "1.0.99"
serde_derive = "1.0.89"
serde_json = "1.0.39"
